@host = http://127.0.0.1:3005

GET {{host}}/posts

###

POST {{host}}/posts
Content-Type: application/json

{
    "name": "Albert",
    "tags": ["測試"],
    "type": "person",
    "content": "test again"
}

###

DELETE {{host}}/posts

###

DELETE {{host}}/posts/663451112992cccb0db94db3


